#
# makefile
#
# Copyright (C) STMicroelectronics Ltd. 2002
#
# Makefile for Configs directory
#

RPC_ROOT = ..

include $(RPC_ROOT)/src/mkfiles/host.mak

all:

clean:


DIST_SRC       = makefile \
		 bootstrap.dbg \
		 bootstrap.lku \
		 rpc_mailbox.cfg \
                 rpc_nodevice.cfg \
		 rpc_st40.cfg \
		 rpc_st40.cmd \
                 st40defs.cmd \
                 st200defs.cmd

include $(RPC_ROOT)/src/mkfiles/install.mak

