#
# Makefile for module providing procfs functionality to enigma2
#
#KDIR = /opt/STM/STLinux-2.3/devkit/build/build-mb442/kernel

#ARCH = sh
#CROSS_COMPILE = sh4-linux-
#PWD = $(shell pwd)


obj-m 		+= e2_proc.o
e2_proc-objs	+= e2_proc_main.o

#all:
	#make ARCH=$(ARCH) CROSS_COMPILE=$(CROSS_COMPILE) -C $(KDIR) M=$(PWD) modules

#clean:
	#-rm -f *.o *.ko .*.cmd .*.flags *.mod.c

